batch_size: 600
dataset_name: expression
encoder_type: small
epochs: 80
eps_std: 0.1
hidden_dim_decoder: 100
latent_dim: 25
learning_rate: 0.001
model_name: gru_expressions
models_path: results/vaes
property_hidden_dim: 100
teacher_forcing: false
