batch_size: 600
dataset_name: molecules
encoder_type: large
epochs: 150
eps_std: 0.01
hidden_dim_decoder: 500
latent_dim: 56
learning_rate: 0.0001
model_name: gru_molecules_tf_True_eps_pp1_dim_56
models_path: results/vaes
teacher_forcing: true
